### ISSUE TITLE
Issue Pagination List Menu Registrasi Mandiri

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#1009]
## Description
Link page : https://lab.pikobar.jabarprov.go.id/registrasi/mandiri
List Error :

1. No urut list data yang ditampilkan tidak urut
2. Ketika pindah page 2 dan seterusnya data yang ditampilkan tidak sesuai ketentuan (no urut & settingan data yg ingin ditampilkan)

## Task

- [x] Crosscheck issue oleh QA
- [x] Tracking issue disisi front end atau backend
- [ ] Solved issue sesuai hasil track issue
- [ ] Inform issue sudah ditangani ke user

**Comment by maruf12** [comment]
Hasil investigasi bug ini dikarenakan ada value statusnya 5. padahal value status yang diperbolehkan cuma 1 - 4.
@erlangganugraha @shintadewiaw @sandisunandar99 @firmanJS

**Comment by sandisunandar99** [comment]
oia yg ini udah di ketahui sumber nya dari mana bisa ngisi status 5?

**Comment by sandisunandar99** [comment]
> oia yg ini udah di ketahui sumber nya dari mana bisa ngisi status 5?
