### ISSUE TITLE
Tambah Peserta RDT

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#66]
## Acceptance Criteria :
* [ ] Terdapat beberapa tipe sasaran diantaranya :
  * [ ] ODP
  * [ ] Kluster
  * [ ] Kontak erat dengan positif
  * [ ] Anggota keluarga PDP
  * [ ] Tenaga kesehatan dizona merah 
* [ ] Terdapat isian form yang berbeda setiap tipe sasarannya, sbb :
  * [ ] ODP : https://www.figma.com/file/RBr5lZdlLOWMPOMgyssD75/Web-Survey?node-id=3976%3A5575
  * [ ] Kluster : https://www.figma.com/file/RBr5lZdlLOWMPOMgyssD75/Web-Survey?node-id=4000%3A5958
  * [ ] Kontak erat dengan positif : https://www.figma.com/file/RBr5lZdlLOWMPOMgyssD75/Web-Survey?node-id=4000%3A6144
  * [ ] Anggota keluarga PDP : https://www.figma.com/file/RBr5lZdlLOWMPOMgyssD75/Web-Survey?node-id=4000%3A6330
  * [ ] Tenaga kesehatan dizona merah : https://www.figma.com/file/RBr5lZdlLOWMPOMgyssD75/Web-Survey?node-id=4000%3A6512
* [ ] Adanya validasi jika peserta sudah terdaftar berupa message, *bisa divalidasi berdasarkan NIK atau No HP
* [ ] Jika pendaftaran berhasil maka direct ke list pendaftaran

## Responsiveness:
- [ ] Laptop with HiDPI
- [ ] Laptop with MDPI
- [ ] Mobile version

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

## Task list:
**Front End**
- [ ] lorem ipsum

**Back End**
- [x] endpoint POST /api/rdt

**UI**
- [ ] lorem ipsum

**UX**
- [ ] lorem ipsum

**Technical Writer**
- [ ] lorem ipsum

**Comment by aliyaqara** [comment]
1. Jika data yang di inputkan sudah ada dalam list, saat menyimpan data muncul "_id 5e7dddb6d7fa1f001250aeea ID already exists in the database."
2. Jika data yang di inputkan sudah ada dalam list sebaiknya pada dropdown cari kasus datanya tidak muncul 
3. id kasus engan status positif muncul di list dropdown cari kasus

@Arif9878 @maruf12

**Comment by maruf12** [comment]
Ini bedanya sama card input hasil apa ya? @erlangganugraha
