### ISSUE TITLE
List Peserta RDT

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#68]
## Mockup :
https://www.figma.com/file/RBr5lZdlLOWMPOMgyssD75/Web-Survey?node-id=4027%3A1

## Acceptance Criteria :
* [ ] Terdapat Filter bedasarkan :
  * [ ] Tampilkan semua
  * [ ] ODP
  * [ ] Kluster
  * [ ] Kontak erat dengan positif
  * [ ] Anggota keluarga PDP
  * [ ] Tenaga kesehatan dizona merah 
* [ ] Terdapat list peserta berdasarkan author
* [ ] By Default urutan list berdasarkan last update terbaru
* [ ] Terdapat button pilih aksi sbb :
  * [ ] Hapus Data Peserta
  * [ ] Input hasil test
* [ ] Terdapat Pencarian berdasarkan nama, no telepon, tipe sasaran
* [ ] Terdapat pagination, by default set 20 rows

## Responsiveness:
- [ ] Laptop with HiDPI
- [ ] Laptop with MDPI
- [ ] Mobile version

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

## Task list:
**Front End**
- [ ] lorem ipsum

**Back End**
- [x] membuat endpoint GET /api/rdt
   * [ ] Terdapat Filter berdasarkan tipe sasaran
   * [ ] pembatasan list peserta berdasarkan author
   * [ ] By Default urutan list berdasarkan last update terbaru
   * [ ] Terdapat Pencarian berdasarkan nama, no telepon, tipe sasaran
   * [ ] Terdapat pagination, by default set 20 rows

**UI**
- [ ] lorem ipsum

**UX**
- [ ] lorem ipsum

**Technical Writer**
- [ ] lorem ipsum

**Comment by aliyaqara** [comment]
1. Jika input selain ODP, id kasus tidak tampil (tetapi jika di list pelaporan kasus id sudah ada dan tampil)
2. Saat input dengan sasaran ODP hasil Negative pada list tampil tidak berada paling atas (mengikuti id kasus)
3. Tidak ada tombol reset untuk serching?
4. Pencarian berdasarkan no telepon dan tipe sasaran belum berfungsi

@Arif9878
