### ISSUE TITLE
Hasil Test Peserta RDT

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#69]
## Mockup
https://www.figma.com/file/RBr5lZdlLOWMPOMgyssD75/Web-Survey?node-id=4013%3A6525

### Functional :
**Halaman List Peserta :**
* [ ] Terdapat button "Input Hasil Test"

**Halaman Input Hasil Test :**
* [ ] Terdapat Detail Peserta
* [ ] Terdapat pilihan Hasil : Negatif , Positif
* [ ] Terdapat Keterangan tambahan
* [ ] Terdapat button "Simpan"
* [ ] Terdapat button "Simpan & Tambahkan Ke Laporan Kasus"
* [ ] Jika memilih button "Simpan & Tambahkan Ke Laporan Kasus" maka direct ke Page Tambah Kasus
* [ ] Jika memilih button "Simpan" maka direct ke list peserta

**Halaman Tambah Kasus :**
* [ ] Otomatis field terisi dari data peserta

## Responsiveness:
- [ ] Laptop with HiDPI
- [ ] Laptop with MDPI
- [ ] Mobile version

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

## Task list:
**Front End**
- [ ] lorem ipsum

**Back End**
- [ ] lorem ipsum

**UI**
- [ ] lorem ipsum

**UX**
- [ ] lorem ipsum

**Technical Writer**
- [ ] lorem ipsum
