### ISSUE TITLE
Hapus data peserta

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#70]
### Functional :
**Halaman List Peserta :**
* [ ] Data tidak bisa dihapus jika sudah ada hasil test
* [ ] Fungsi hapus bertipe soft delete
* [ ] Muncul pop-up validasi "Anda yakin ingin menghapus data ini?"

## Responsiveness:
- [ ] Laptop with HiDPI
- [ ] Laptop with MDPI
- [ ] Mobile version

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

## Task list:
**Front End**
- [ ] lorem ipsum

**Back End**
- [ ] lorem ipsum

**UI**
- [ ] lorem ipsum

**UX**
- [ ] lorem ipsum

**Technical Writer**
- [ ] lorem ipsum
