### ISSUE TITLE
Detail data peserta

### ISSUE THREAD

**Issue by erlangganugraha** [jabardigitalservice/pikobar-pelaporan-frontend#71]
## Acceptance Criteria
**Halaman Detail Data Peserta :**
* [ ] Terdapat Detail Peserta
* [ ] Terdapat button "Kembali ke List Peserta"

## Responsiveness:
- [ ] Laptop with HiDPI
- [ ] Laptop with MDPI
- [ ] Mobile version

## Cross-browser compatibility:
- [ ] Chrome
- [ ] Firefox

## Task list:
**Front End**
- [ ] lorem ipsum

**Back End**
- [ ] Membuat API detail peserta

**UI**
- [ ] lorem ipsum

**UX**
- [ ] lorem ipsum

**Technical Writer**
- [ ] lorem ipsum

**Comment by alifianif** [comment]
1. Kategori peserta tidak muncul di detail. Apakah kategori peserta dirahasiakan atau memang tidak ditampilkan di detail?
2. Tidak terdapat button "Kembali ke List Peserta". Tidak disertakan mock up jadi saya juga tidak tahu apakah memang seharusnya ada button ini atau tidak? tapi di acceptance criteria ada, jadi saya juga mempertanyakan hal tsb.

@erlangganugraha @maruf12 @Arif9878

**Comment by Arif9878** [comment]
> 1. Kategori peserta tidak muncul di detail. Apakah kategori peserta dirahasiakan atau memang tidak ditampilkan di detail?
> 2. Tidak terdapat button "Kembali ke List Peserta". Tidak disertakan mock up jadi saya juga tidak tahu apakah memang seharusnya ada button ini atau tidak? tapi di acceptance criteria ada, jadi saya juga mempertanyakan hal tsb.
> 
> @erlangganugraha @maruf12 @Arif9878

**Comment by Arif9878** [comment]
> > 1. Kategori peserta tidak muncul di detail. Apakah kategori peserta dirahasiakan atau memang tidak ditampilkan di detail?
> > 2. Tidak terdapat button "Kembali ke List Peserta". Tidak disertakan mock up jadi saya juga tidak tahu apakah memang seharusnya ada button ini atau tidak? tapi di acceptance criteria ada, jadi saya juga mempertanyakan hal tsb.
> > 
> > @erlangganugraha @maruf12 @Arif9878

**Comment by Arif9878** [comment]
aku sesuain dulu lif

**Comment by Arif9878** [comment]
@alifianif bisa di test lagi lif detail nya

**Comment by alifianif** [comment]
@Arif9878 Okeey udah solve mas untuk issue yang saya tulis di atas. Tapi ada sedikit tambahan, tapi sepertinya akan dilanjut di card sebelah. Thank you ^^
